"""second

Revision ID: 6aa6a948194b
Revises: 321d200cd57d
Create Date: 2024-01-01 12:58:24.863765

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6aa6a948194b'
down_revision: Union[str, None] = '321d200cd57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'ip')
    # ### end Alembic commands ###
