"""fourth

Revision ID: ed4b11eb7121
Revises: 9e0741011fb6
Create Date: 2024-01-01 20:43:38.118281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4b11eb7121'
down_revision: Union[str, None] = '9e0741011fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('city', sa.String(), nullable=True))
    op.add_column('userdata', sa.Column('country', sa.String(), nullable=True))
    op.add_column('userdata', sa.Column('region', sa.String(), nullable=True))
    op.drop_column('userdata', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('userdata', 'region')
    op.drop_column('userdata', 'country')
    op.drop_column('userdata', 'city')
    # ### end Alembic commands ###
